#' Plot an AlgaeScan UMAP
#'
#' Visualizes UMAP coordinates generated by [AlgaeScan_umap()].
#' Points can be coloured by a categorical variable, a continuous
#' probability variable, or selected strains can be highlighted.
#'
#' @param data A data.frame or data.table containing `UMAP1` and `UMAP2`,
#'   or the list returned by [AlgaeScan_umap()].
#'
#' @param color_by Character string giving the column used to colour points.
#'   For example `"type"`, `"type_predicted"`, `"algae_prob"` or `"Species"`.
#'
#' @param point_size Point size. Default is `0.5`.
#'
#' @param show_legend Logical. If `TRUE`, display the legend.
#'   Default is `FALSE`.
#'
#' @param legend_title Optional legend title.
#'
#' @param legend_position Optional ggplot2 legend position.
#'
#' @param continuous Logical. If `TRUE`, treat `color_by` as a continuous
#'   variable. If `NULL`, numeric variables are detected automatically.
#'
#' @param highlight_strains Optional character vector containing strains
#'   to highlight.
#'
#' @param strain_col Character string containing strain identifiers.
#'   Default is `"Species"` for compatibility with the original dataset.
#'
#' @param highlight_label Label used when highlighted strains are grouped.
#'   Default is `"Untrained strains"`.
#'
#' @param highlight_subset_by Optional column used to restrict highlighting.
#'   For example `"type"`.
#'
#' @param highlight_subset_value Optional value used together with
#'   `highlight_subset_by`. For example `"algae"`.
#'
#' @param label_map Optional named character vector used to rename displayed
#'   categorical labels.
#'
#' @param colors Optional named character vector defining colours for
#'   categorical groups. Names must correspond to the displayed values
#'   of `color_by`. For example:
#'   `c("RCC69" = "#FFFF00", "RCC128" = "#B2DF8A")`.
#'
#' @param color_order Optional character vector defining the order of
#'   categories in the legend. Extra categories are allowed, which is
#'   useful when multiple plots should share the same legend order.
#'
#' @param title Optional plot title. Default is `NULL`.
#'
#' @param x_lab Label for the x axis. Default is `"UMAP1"`.
#'
#' @param y_lab Label for the y axis. Default is `"UMAP2"`.
#'
#' @param size_axis_text Axis text size. Default is `18`.
#'
#' @param size_axis_title Axis title size. Default is `20`.
#'
#' @param size_title Plot title size. Default is `20`.
#'
#' @param highlight_mode Highlighting mode. `"group"` places all selected
#'   strains into one category. `"individual"` colours each selected strain
#'   separately and places all remaining events into `"Other events"`.
#'
#' @param highlight_colors Optional named character vector defining colours
#'   for highlighted groups or strains.
#'
#' @return A ggplot object.
#'
#' @examples
#' \dontrun{
#'
#' AlgaeScan_plot_umap(
#'   data = umap_df,
#'   color_by = "type",
#'   show_legend = TRUE
#' )
#'
#' strain_colors <- c(
#'   "RCC69" = "#FFFF00",
#'   "RCC128" = "#B2DF8A"
#' )
#'
#' AlgaeScan_plot_umap(
#'   data = umap_df,
#'   color_by = "Species",
#'   colors = strain_colors,
#'   show_legend = TRUE,
#'   legend_title = "Strain"
#' )
#'
#' }
#'
#' @export
AlgaeScan_plot_umap <- function(
    data,
    color_by = "type",
    point_size = 0.5,
    show_legend = FALSE,
    legend_title = NULL,
    legend_position = NULL,
    continuous = NULL,
    highlight_strains = NULL,
    strain_col = "Species",
    highlight_label = "Untrained strains",
    highlight_subset_by = NULL,
    highlight_subset_value = NULL,
    label_map = NULL,
    colors = NULL,
    color_order = NULL,
    title = NULL,
    x_lab = "UMAP1",
    y_lab = "UMAP2",
    size_axis_text = 18,
    size_axis_title = 20,
    size_title = 20,
    highlight_mode = c("group", "individual"),
    highlight_colors = NULL
) {
  
  # ============================================================
  # 1. Extract UMAP data
  # ============================================================
  
  if (
    is.list(data) &&
    !is.data.frame(data) &&
    !is.null(data$umap_df)
  ) {
    
    data <- data$umap_df
  }
  
  
  if (!is.data.frame(data)) {
    
    stop(
      "`data` must be a data.frame, data.table, or an object ",
      "returned by `AlgaeScan_umap()`."
    )
  }
  
  
  data <- data.table::as.data.table(
    data.table::copy(data)
  )
  
  
  # ============================================================
  # 2. Check required columns
  # ============================================================
  
  required_cols <- c(
    "UMAP1",
    "UMAP2",
    color_by
  )
  
  
  missing_cols <- required_cols[
    !required_cols %in% colnames(data)
  ]
  
  
  if (length(missing_cols) > 0) {
    
    stop(
      paste0(
        "The following required column(s) are missing: ",
        paste(
          missing_cols,
          collapse = ", "
        )
      )
    )
  }
  
  
  # ============================================================
  # 3. Determine colour type
  # ============================================================
  
  if (is.null(continuous)) {
    
    continuous <- is.numeric(
      data[[color_by]]
    )
  }
  
  
  # ============================================================
  # 4. Prepare categorical colour layer
  # ============================================================
  
  if (!continuous) {
    
    highlight_mode <- match.arg(
      highlight_mode
    )
    
    
    # ----------------------------------------------------------
    # Initial plotting groups
    # ----------------------------------------------------------
    
    data[
      ,
      .plot_group := as.character(
        get(color_by)
      )
    ]
    
    
    # ----------------------------------------------------------
    # Standard AlgaeScan display labels
    # ----------------------------------------------------------
    
    data[
      .plot_group == "algae",
      .plot_group := "Algae"
    ]
    
    
    data[
      .plot_group %in% c(
        "non_algae",
        "non-algae"
      ),
      .plot_group := "Non-algae"
    ]
    
    
    # ----------------------------------------------------------
    # Optional custom labels
    # ----------------------------------------------------------
    
    if (!is.null(label_map)) {
      
      if (is.null(names(label_map))) {
        
        stop(
          "`label_map` must be a named character vector."
        )
      }
      
      
      current_values <- data$.plot_group
      
      
      replace_values <- current_values %in%
        names(label_map)
      
      
      current_values[
        replace_values
      ] <- unname(
        label_map[
          current_values[
            replace_values
          ]
        ]
      )
      
      
      data[
        ,
        .plot_group := current_values
      ]
    }
    
    
    # ============================================================
    # 5. Highlight selected strains
    # ============================================================
    
    if (!is.null(highlight_strains)) {
      
      if (!strain_col %in% colnames(data)) {
        
        stop(
          paste0(
            "Strain column `",
            strain_col,
            "` was not found."
          )
        )
      }
      
      
      highlight_rows <- data[[strain_col]] %in%
        highlight_strains
      
      
      # --------------------------------------------------------
      # Optional subset restriction
      # --------------------------------------------------------
      
      if (!is.null(highlight_subset_by)) {
        
        if (!highlight_subset_by %in% colnames(data)) {
          
          stop(
            paste0(
              "Highlight subset column `",
              highlight_subset_by,
              "` was not found."
            )
          )
        }
        
        
        if (is.null(highlight_subset_value)) {
          
          stop(
            "`highlight_subset_value` must be supplied when ",
            "`highlight_subset_by` is used."
          )
        }
        
        
        highlight_rows <- highlight_rows &
          data[[highlight_subset_by]] %in%
          highlight_subset_value
      }
      
      
      # --------------------------------------------------------
      # Group selected strains together
      # --------------------------------------------------------
      
      if (highlight_mode == "group") {
        
        data[
          highlight_rows,
          .plot_group := highlight_label
        ]
      }
      
      
      # --------------------------------------------------------
      # Colour selected strains individually
      # --------------------------------------------------------
      
      if (highlight_mode == "individual") {
        
        data[
          ,
          .plot_group := "Other events"
        ]
        
        
        data[
          highlight_rows,
          .plot_group := as.character(
            get(strain_col)
          )
        ]
      }
    }
    
    
    # ============================================================
    # 6. Determine category order
    # ============================================================
    
    plot_groups <- unique(
      as.character(
        data$.plot_group
      )
    )
    
    
    if (!is.null(color_order)) {
      
      missing_order <- setdiff(
        plot_groups,
        color_order
      )
      
      
      if (length(missing_order) > 0) {
        
        stop(
          paste0(
            "`color_order` is missing the following displayed group(s): ",
            paste(
              missing_order,
              collapse = ", "
            )
          )
        )
      }
      
      
      data[
        ,
        .plot_group := factor(
          .plot_group,
          levels = unique(color_order)
        )
      ]
      
      
    } else if (
      !is.null(highlight_strains) &&
      highlight_mode == "individual"
    ) {
      
      selected_groups <- unique(
        as.character(
          data$.plot_group[
            data$.plot_group != "Other events"
          ]
        )
      )
      
      
      individual_order <- c(
        "Other events",
        selected_groups
      )
      
      
      data[
        ,
        .plot_group := factor(
          .plot_group,
          levels = individual_order
        )
      ]
      
      
      color_order <- individual_order
    }
  }
  
  
  # ============================================================
  # 7. Build plot
  # ============================================================
  
  if (continuous) {
    
    gg_plot <- ggplot2::ggplot(
      data,
      ggplot2::aes(
        x = UMAP1,
        y = UMAP2,
        color = .data[[color_by]]
      )
    ) +
      ggplot2::geom_point(
        size = point_size
      ) +
      ggplot2::scale_color_gradientn(
        colors = c(
          "lavender",
          "orchid",
          "mediumorchid",
          "purple",
          "purple4"
        )
      )
    
  } else {
    
    gg_plot <- ggplot2::ggplot(
      data,
      ggplot2::aes(
        x = UMAP1,
        y = UMAP2,
        color = .plot_group
      )
    ) +
      ggplot2::geom_point(
        size = point_size
      )
    
    
    # ============================================================
    # 8. Categorical colours
    # ============================================================
    
    plot_groups <- unique(
      as.character(
        data$.plot_group
      )
    )
    
    
    manual_colors <- NULL
    
    
    # ----------------------------------------------------------
    # User-defined general colours
    # ----------------------------------------------------------
    
    if (!is.null(colors)) {
      
      if (is.null(names(colors))) {
        
        stop(
          "`colors` must be a named character vector."
        )
      }
      
      
      manual_colors <- colors
    }
    
    
    # ----------------------------------------------------------
    # Optional highlight-specific colours
    # ----------------------------------------------------------
    
    if (!is.null(highlight_colors)) {
      
      if (is.null(names(highlight_colors))) {
        
        stop(
          "`highlight_colors` must be a named character vector."
        )
      }
      
      
      if (is.null(manual_colors)) {
        
        manual_colors <- highlight_colors
        
      } else {
        
        manual_colors[
          names(highlight_colors)
        ] <- highlight_colors
      }
    }
    
    
    # ----------------------------------------------------------
    # Complete colours for individual highlight mode
    # ----------------------------------------------------------
    
    if (
      !is.null(highlight_strains) &&
      highlight_mode == "individual" &&
      is.null(colors)
    ) {
      
      strain_groups <- setdiff(
        plot_groups,
        "Other events"
      )
      
      
      automatic_strain_colors <- stats::setNames(
        grDevices::hcl.colors(
          length(strain_groups),
          palette = "Dark 3"
        ),
        strain_groups
      )
      
      
      automatic_colors <- c(
        "Other events" = "grey80",
        automatic_strain_colors
      )
      
      
      if (is.null(manual_colors)) {
        
        manual_colors <- automatic_colors
        
      } else {
        
        missing_manual <- setdiff(
          names(automatic_colors),
          names(manual_colors)
        )
        
        
        manual_colors <- c(
          manual_colors,
          automatic_colors[
            missing_manual
          ]
        )
      }
    }
    
    
    # ----------------------------------------------------------
    # Standard AlgaeScan colours
    # ----------------------------------------------------------
    
    if (is.null(manual_colors)) {
      
      standard_groups <- c(
        "Algae",
        "Non-algae",
        "Untrained strains"
      )
      
      
      if (all(plot_groups %in% standard_groups)) {
        
        manual_colors <- c(
          "Algae" = "#E69F00",
          "Non-algae" = "#0072B2",
          "Untrained strains" = "#00C853"
        )
      }
    }
    
    
    # ----------------------------------------------------------
    # Apply manual colours when available
    # ----------------------------------------------------------
    
    if (!is.null(manual_colors)) {
      
      missing_colors <- setdiff(
        plot_groups,
        names(manual_colors)
      )
      
      
      if (length(missing_colors) > 0) {
        
        stop(
          paste0(
            "No colour was supplied for the following displayed group(s): ",
            paste(
              missing_colors,
              collapse = ", "
            )
          )
        )
      }
      
      
      if (is.null(color_order)) {
        
        color_order <- plot_groups
      }
      
      
      gg_plot <- gg_plot +
        ggplot2::scale_color_manual(
          values = manual_colors,
          breaks = color_order
        )
    }
  }
  
  
  # ============================================================
  # 9. Plot labels and appearance
  # ============================================================
  
  if (is.null(legend_title)) {
    
    legend_title <- color_by
  }
  
  
  gg_plot <- gg_plot +
    ggplot2::labs(
      title = title,
      x = x_lab,
      y = y_lab,
      color = legend_title
    ) +
    ggplot2::theme(
      
      plot.title = ggplot2::element_text(
        size = size_title,
        face = "bold",
        hjust = 0.5
      ),
      
      axis.text = ggplot2::element_text(
        size = size_axis_text
      ),
      
      axis.title.x = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      ),
      
      axis.title.y = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      ),
      
      panel.grid.major = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.background = ggplot2::element_blank(),
      
      axis.line = ggplot2::element_line(
        colour = "black"
      ),
      
      plot.margin = grid::unit(
        c(0.5, 0.5, 0.5, 0.5),
        "cm"
      ),
      
      legend.key.size = grid::unit(
        1,
        "cm"
      ),
      
      legend.title = ggplot2::element_text(
        size = 20
      ),
      
      legend.text = ggplot2::element_text(
        size = 20
      )
    )
  
  
  # ============================================================
  # 10. Legend
  # ============================================================
  
  if (!show_legend) {
    
    gg_plot <- gg_plot +
      ggplot2::theme(
        legend.position = "none"
      )
    
  } else {
    
    gg_plot <- gg_plot +
      ggplot2::guides(
        color = ggplot2::guide_legend(
          override.aes = list(
            size = 5
          )
        )
      )
  }
  
  
  if (
    !is.null(legend_position) &&
    show_legend
  ) {
    
    gg_plot <- gg_plot +
      ggplot2::theme(
        legend.position = legend_position
      )
  }
  
  
  # ============================================================
  # 11. Return plot
  # ============================================================
  
  return(
    gg_plot
  )
}

#' Plot a confusion matrix
#'
#' Creates a confusion matrix comparing reference and predicted
#' classification labels.
#'
#' Each cell shows the number of events and the percentage relative
#' to the corresponding reference class.
#'
#' @param y_truth Vector containing the reference class labels.
#'
#' @param y_pred Vector containing the predicted class labels.
#'
#' @param label_map Optional named character vector used to rename
#'   class labels for plotting.
#'
#' @param x_lab Label for the x axis. Default is `"Reference"`.
#'
#' @param y_lab Label for the y axis. Default is `"Predicted"`.
#'
#' @param size_axis_text Numeric value controlling axis text size.
#'   Default is `18`.
#'
#' @param size_title_x Numeric value controlling the x-axis title size.
#'   Default is `20`.
#'
#' @param size_title_y Numeric value controlling the y-axis title size.
#'   Default is `20`.
#'
#' @param show_legend Logical. If `TRUE`, display the colour-scale legend.
#'   Default is `FALSE`.
#'
#' @return A ggplot object containing the confusion matrix.
#'
#' @export
AlgaeScan_confusion_matrix <- function(
    y_truth,
    y_pred,
    label_map = NULL,
    x_lab = "Reference",
    y_lab = "Predicted",
    size_axis_text = 18,
    size_title_x = 20,
    size_title_y = 20,
    show_legend = FALSE
) {
  
  # ============================================================
  # 1. Check input
  # ============================================================
  
  if (length(y_truth) != length(y_pred)) {
    stop(
      "`y_truth` and `y_pred` must have the same length."
    )
  }
  
  if (length(y_truth) == 0) {
    stop(
      "`y_truth` and `y_pred` contain no observations."
    )
  }
  
  if (any(is.na(y_truth)) || any(is.na(y_pred))) {
    stop(
      "`y_truth` and `y_pred` cannot contain missing values."
    )
  }
  
  
  y_truth <- as.character(
    y_truth
  )
  
  y_pred <- as.character(
    y_pred
  )
  
  
  # ============================================================
  # 2. Rename class labels
  # ============================================================
  
  if (!is.null(label_map)) {
    
    if (is.null(names(label_map))) {
      stop(
        "`label_map` must be a named character vector."
      )
    }
    
    
    truth_match <- y_truth %in% names(
      label_map
    )
    
    pred_match <- y_pred %in% names(
      label_map
    )
    
    
    y_truth[truth_match] <- unname(
      label_map[
        y_truth[truth_match]
      ]
    )
    
    y_pred[pred_match] <- unname(
      label_map[
        y_pred[pred_match]
      ]
    )
  }
  
  
  # ============================================================
  # 3. Build confusion matrix
  # ============================================================
  
  conf_matrix <- table(
    Predicted = y_pred,
    Reference = y_truth
  )
  
  
  conf_df <- as.data.frame(
    conf_matrix
  )
  
  
  # ============================================================
  # 4. Calculate proportions within each reference class
  # ============================================================
  
  conf_df$Proportion <- mapply(
    function(freq, reference) {
      
      freq / sum(
        conf_df$Freq[
          conf_df$Reference == reference
        ]
      )
      
    },
    conf_df$Freq,
    conf_df$Reference
  )
  
  
  # ============================================================
  # 5. Add count and percentage labels
  # ============================================================
  
  conf_df$Label <- sprintf(
    "%d\n(%.1f%%)",
    conf_df$Freq,
    conf_df$Proportion * 100
  )
  
  
  # ============================================================
  # 6. Plot
  # ============================================================
  
  gg_plot <- ggplot2::ggplot(
    conf_df,
    ggplot2::aes(
      x = Reference,
      y = Predicted,
      fill = Proportion
    )
  ) +
    ggplot2::geom_tile(
      color = "white"
    ) +
    ggplot2::geom_text(
      ggplot2::aes(
        label = Label
      ),
      color = "white",
      size = 6
    ) +
    ggplot2::scale_fill_gradient(
      low = "#001F3F",
      high = "#E36414"
    ) +
    ggplot2::labs(
      title = NULL,
      x = x_lab,
      y = y_lab
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      
      axis.text = ggplot2::element_text(
        size = size_axis_text
      ),
      
      axis.title.x = ggplot2::element_text(
        size = size_title_x,
        face = "bold"
      ),
      
      axis.title.y = ggplot2::element_text(
        size = size_title_y,
        face = "bold"
      ),
      
      axis.ticks.y.right = ggplot2::element_blank(),
      axis.ticks.x.top = ggplot2::element_blank(),
      axis.text.x.top = ggplot2::element_blank(),
      axis.text.y.right = ggplot2::element_blank(),
      
      panel.grid.major = ggplot2::element_blank(),
      
      legend.key.size = grid::unit(
        1,
        "cm"
      ),
      
      legend.title = ggplot2::element_text(
        size = 20
      ),
      
      legend.text = ggplot2::element_text(
        size = 20
      )
    )
  
  
  if (!show_legend) {
    
    gg_plot <- gg_plot +
      ggplot2::theme(
        legend.position = "none"
      )
  }
  
  
  return(gg_plot)
}


#' Plot per-class F1 scores
#'
#' Creates a bar plot of class-specific F1 scores returned by
#' [AlgaeScan_f1()] when `multiclass = TRUE`.
#'
#' This function is useful for visualizing classification performance
#' across multiple classes, such as phytoplankton strains classified
#' by Model B.
#'
#' @param f1_result Multiclass result returned by [AlgaeScan_f1()].
#'   The object must contain an `all_scores` element with one F1 score
#'   for each class.
#'
#' @param class_order Optional character vector defining the order of
#'   classes along the x axis. If `NULL`, classes are ordered according
#'   to `sort_by`.
#'
#' @param sort_by Character string controlling automatic class ordering
#'   when `class_order = NULL`. One of `"decreasing"`, `"increasing"`
#'   or `"none"`. Default is `"decreasing"`.
#'
#' @param x_lab Label for the x axis. Default is `"Strain"`.
#'
#' @param y_lab Label for the y axis. Default is `"F1 score"`.
#'
#' @param y_limits Numeric vector of length two defining the y-axis
#'   limits. Default is `c(0, 1)`.
#'
#' @param bar_fill Fill colour used for bars. Default is `"grey40"`.
#'
#' @param bar_width Width of bars. Default is `0.8`.
#'
#' @param show_values Logical. If `TRUE`, display the F1 value above
#'   each bar. Default is `FALSE`.
#'
#' @param value_digits Number of decimal places used for displayed
#'   F1 values. Default is `2`.
#'
#' @param show_mean Logical. If `TRUE`, add a dashed horizontal line
#'   showing the mean F1 score across classes. Default is `FALSE`.
#'
#' @param rotate_x Numeric angle used to rotate x-axis labels.
#'   Default is `45`.
#'
#' @param size_axis_text Axis text size. Default is `18`.
#'
#' @param size_axis_title Axis title size. Default is `20`.
#'
#' @return A ggplot object.
#'
#' @examples
#' \dontrun{
#'
#' f1_out <- AlgaeScan_f1(
#'   y_truth = prediction$Species,
#'   y_pred = prediction$species_predicted,
#'   multiclass = TRUE
#' )
#'
#' AlgaeScan_plot_f1(
#'   f1_result = f1_out
#' )
#'
#' }
#'
#' @export
AlgaeScan_plot_f1 <- function(
    f1_result,
    class_order = NULL,
    sort_by = c("decreasing", "increasing", "none"),
    x_lab = "Strain",
    y_lab = "F1 score",
    y_limits = c(0, 1),
    bar_fill = "grey40",
    bar_width = 0.8,
    show_values = FALSE,
    value_digits = 2,
    show_mean = FALSE,
    rotate_x = 45,
    size_axis_text = 18,
    size_axis_title = 20
) {
  
  # ============================================================
  # 1. Check F1 result
  # ============================================================
  
  if (!is.list(f1_result)) {
    
    stop(
      "`f1_result` must be the multiclass result returned by `AlgaeScan_f1()`."
    )
  }
  
  
  if (is.null(f1_result$all_scores)) {
    
    stop(
      paste0(
        "`f1_result` does not contain class-specific F1 scores. ",
        "Run `AlgaeScan_f1(..., multiclass = TRUE)` first."
      )
    )
  }
  
  
  f1_scores <- f1_result$all_scores
  
  
  if (!is.numeric(f1_scores)) {
    
    stop(
      "`f1_result$all_scores` must be numeric."
    )
  }
  
  
  if (is.null(names(f1_scores))) {
    
    stop(
      "`f1_result$all_scores` must contain class names."
    )
  }
  
  
  # ============================================================
  # 2. Prepare plotting data
  # ============================================================
  
  class_names <- names(
    f1_scores
  )
  
  
  # caret adds "Class: " to multiclass row names
  class_names <- sub(
    "^Class: ",
    "",
    class_names
  )
  
  
  plot_data <- data.table::data.table(
    class = class_names,
    f1 = as.numeric(f1_scores)
  )
  
  
  # Remove undefined F1 scores
  if (anyNA(plot_data$f1)) {
    
    warning(
      "Classes with undefined F1 scores were removed from the plot.",
      call. = FALSE
    )
    
    plot_data <- plot_data[
      !is.na(f1)
    ]
  }
  
  
  if (nrow(plot_data) == 0) {
    
    stop(
      "No valid F1 scores are available for plotting."
    )
  }
  
  
  # ============================================================
  # 3. Determine class order
  # ============================================================
  
  if (!is.null(class_order)) {
    
    missing_classes <- setdiff(
      plot_data$class,
      class_order
    )
    
    
    if (length(missing_classes) > 0) {
      
      stop(
        paste0(
          "`class_order` is missing the following class(es): ",
          paste(
            missing_classes,
            collapse = ", "
          )
        )
      )
    }
    
    
    class_order <- class_order[
      class_order %in% plot_data$class
    ]
    
    
  } else {
    
    sort_by <- match.arg(
      sort_by
    )
    
    
    if (sort_by == "decreasing") {
      
      class_order <- plot_data[
        order(f1, decreasing = TRUE),
        class
      ]
      
    } else if (sort_by == "increasing") {
      
      class_order <- plot_data[
        order(f1),
        class
      ]
      
    } else {
      
      class_order <- plot_data$class
    }
  }
  
  
  plot_data[
    ,
    class := factor(
      class,
      levels = class_order
    )
  ]
  
  
  # ============================================================
  # 4. Check plot settings
  # ============================================================
  
  if (
    !is.numeric(y_limits) ||
    length(y_limits) != 2 ||
    y_limits[1] >= y_limits[2]
  ) {
    
    stop(
      "`y_limits` must contain two increasing numeric values."
    )
  }
  
  
  if (
    !is.numeric(bar_width) ||
    length(bar_width) != 1 ||
    bar_width <= 0
  ) {
    
    stop(
      "`bar_width` must be a positive numeric value."
    )
  }
  
  
  # ============================================================
  # 5. Create plot
  # ============================================================
  
  p <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      x = class,
      y = f1
    )
  ) +
    ggplot2::geom_col(
      fill = bar_fill,
      width = bar_width
    ) +
    ggplot2::scale_y_continuous(
      limits = y_limits,
      expand = ggplot2::expansion(
        mult = c(0, 0.05)
      )
    ) +
    ggplot2::labs(
      x = x_lab,
      y = y_lab
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.text = ggplot2::element_text(
        size = size_axis_text
      ),
      axis.text.x = ggplot2::element_text(
        angle = rotate_x,
        vjust = 1,
        hjust = 1
      ),
      axis.title.x = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      ),
      axis.title.y = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      )
    )
  
  
  # ============================================================
  # 6. Optional F1 values
  # ============================================================
  
  if (show_values) {
    
    p <- p +
      ggplot2::geom_text(
        ggplot2::aes(
          label = round(
            f1,
            value_digits
          )
        ),
        vjust = -0.3,
        size = 4
      )
  }
  
  
  # ============================================================
  # 7. Optional mean F1 line
  # ============================================================
  
  if (show_mean) {
    
    mean_f1 <- mean(
      plot_data$f1,
      na.rm = TRUE
    )
    
    
    p <- p +
      ggplot2::geom_hline(
        yintercept = mean_f1,
        linetype = "dashed",
        linewidth = 0.7
      )
  }
  
  
  # ============================================================
  # 8. Return plot
  # ============================================================
  
  return(
    p
  )
}


#' Plot repeated cross-validation results
#'
#' Creates a line plot showing cross-validation performance across
#' repetitions for multiple models.
#'
#' The function accepts either a `score` column or an `accuracy`
#' column. If both are present, `score` is used by default.
#'
#' @param data A `data.frame` or `data.table` containing repeated
#'   cross-validation results.
#' @param repetition_col Character string giving the repetition column.
#'   Default is `"repetition"`.
#' @param model_col Character string giving the model-name column.
#'   Default is `"model"`.
#' @param score_col Character string giving the score column.
#'   Default is `"score"`.
#' @param x_lab X-axis label.
#' @param y_lab Y-axis label.
#' @param legend_title Legend title. Default is `"Model"`.
#' @param model_order Optional character vector specifying model order
#'   in the legend.
#' @param model_labels Optional named character vector for custom legend
#'   labels. Names should match model values.
#' @param colors Optional named character vector of colours for models.
#' @param linetypes Optional named character vector of linetypes for models.
#' @param point_size Size of points. Default is `4`.
#' @param line_size Size of lines. Default is `1.5`.
#' @param alpha_line Line alpha. Default is `1`.
#' @param size_axis_text Axis tick text size. Default is `20`.
#' @param size_axis_title Axis title size. Default is `26`.
#' @param size_legend_text Legend text size. Default is `18`.
#' @param size_legend_title Legend title size. Default is `20`.
#' @param show_legend Logical. Default is `TRUE`.
#' @param legend_position Legend position. Default is `"right"`.
#' @param legend_ncol Number of legend columns. Default is `1`.
#' @param legend_key_height Height of each legend key.
#'   Default is `grid::unit(0.9, "cm")`.
#' @param legend_key_width Width of each legend key.
#'   Default is `grid::unit(1.4, "cm")`.
#' @param legend_spacing_y Vertical spacing between legend rows.
#'   Default is `grid::unit(0.25, "cm")`.
#' @param legend_symbol_size Size of symbols shown in the legend.
#'   Default is `5`.
#' @param y_limits Optional numeric vector of length 2 for y-axis limits.
#' @param y_breaks Optional numeric vector for y-axis breaks.
#'
#' @return A `ggplot2` object.
#'
#' @export
AlgaeScan_plot_cv_repetitions <- function(
    data,
    repetition_col = "repetition",
    model_col = "model",
    score_col = "score",
    x_lab = "Repetition",
    y_lab = "Cross-validation accuracy",
    legend_title = "Model",
    model_order = NULL,
    model_labels = NULL,
    colors = NULL,
    linetypes = NULL,
    point_size = 4,
    line_size = 1.5,
    alpha_line = 1,
    size_axis_text = 20,
    size_axis_title = 26,
    size_legend_text = 18,
    size_legend_title = 20,
    show_legend = TRUE,
    legend_position = "right",
    legend_ncol = 1,
    legend_key_height = grid::unit(0.9, "cm"),
    legend_key_width = grid::unit(1.4, "cm"),
    legend_spacing_y = grid::unit(0.25, "cm"),
    legend_symbol_size = 5,
    y_limits = NULL,
    y_breaks = NULL
) {
  
  # ------------------------------------------------------------
  # 1. Checks
  # ------------------------------------------------------------
  
  if (!is.data.frame(data)) {
    stop("`data` must be a data.frame or data.table.")
  }
  
  data <- data.table::as.data.table(data.table::copy(data))
  
  required_cols <- c(repetition_col, model_col)
  missing_cols <- required_cols[!required_cols %in% colnames(data)]
  
  if (length(missing_cols) > 0) {
    stop(
      paste0(
        "Missing required column(s): ",
        paste(missing_cols, collapse = ", ")
      )
    )
  }
  
  if (!score_col %in% colnames(data)) {
    
    if ("accuracy" %in% colnames(data)) {
      score_col <- "accuracy"
    } else {
      stop(
        paste0(
          "Missing required column `", score_col,
          "`. If your data uses another score column, set `score_col` explicitly."
        )
      )
    }
  }
  
  # ------------------------------------------------------------
  # 2. Prepare plotting data
  # ------------------------------------------------------------
  
  plot_data <- data[
    ,
    .(
      repetition = get(repetition_col),
      model = as.character(get(model_col)),
      score_value = as.numeric(get(score_col))
    )
  ]
  
  if (anyNA(plot_data$score_value)) {
    warning("Some score values are NA and will be plotted as missing.", call. = FALSE)
  }
  
  if (is.null(model_order)) {
    model_order <- unique(plot_data$model)
  }
  
  plot_data[
    ,
    model := factor(model, levels = model_order)
  ]
  
  # ------------------------------------------------------------
  # 3. Build plot
  # ------------------------------------------------------------
  
  gg_plot <- ggplot2::ggplot(
    plot_data,
    ggplot2::aes(
      x = repetition,
      y = score_value,
      color = model,
      linetype = model,
      group = model
    )
  ) +
    ggplot2::geom_line(
      linewidth = line_size,
      alpha = alpha_line
    ) +
    ggplot2::geom_point(
      size = point_size
    ) +
    ggplot2::labs(
      x = x_lab,
      y = y_lab,
      color = legend_title,
      linetype = legend_title
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      axis.title.x = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      ),
      axis.title.y = ggplot2::element_text(
        size = size_axis_title,
        face = "bold"
      ),
      axis.text = ggplot2::element_text(
        size = size_axis_text
      ),
      legend.position = if (show_legend) legend_position else "none",
      legend.title = ggplot2::element_text(
        size = size_legend_title,
        face = "bold"
      ),
      legend.text = ggplot2::element_text(
        size = size_legend_text
      ),
      legend.key.height = legend_key_height,
      legend.key.width = legend_key_width,
      legend.spacing.y = legend_spacing_y
    ) +
    ggplot2::guides(
      color = ggplot2::guide_legend(
        ncol = legend_ncol,
        byrow = TRUE,
        override.aes = list(
          linewidth = line_size + 0.4,
          size = legend_symbol_size,
          alpha = 1
        )
      ),
      linetype = ggplot2::guide_legend(
        ncol = legend_ncol,
        byrow = TRUE
      )
    )
  
  # ------------------------------------------------------------
  # 4. Optional manual labels
  # ------------------------------------------------------------
  
  if (!is.null(model_labels)) {
    gg_plot <- gg_plot +
      ggplot2::scale_color_discrete(labels = model_labels) +
      ggplot2::scale_linetype_discrete(labels = model_labels)
  }
  
  # ------------------------------------------------------------
  # 5. Optional manual colours
  # ------------------------------------------------------------
  
  if (!is.null(colors)) {
    gg_plot <- gg_plot +
      ggplot2::scale_color_manual(
        values = colors,
        breaks = model_order,
        labels = if (is.null(model_labels)) model_order else model_labels[model_order]
      )
  }
  
  # ------------------------------------------------------------
  # 6. Optional manual linetypes
  # ------------------------------------------------------------
  
  if (!is.null(linetypes)) {
    gg_plot <- gg_plot +
      ggplot2::scale_linetype_manual(
        values = linetypes,
        breaks = model_order,
        labels = if (is.null(model_labels)) model_order else model_labels[model_order]
      )
  }
  
  # ------------------------------------------------------------
  # 7. Optional y-axis settings
  # ------------------------------------------------------------
  
  if (!is.null(y_limits) || !is.null(y_breaks)) {
    gg_plot <- gg_plot +
      ggplot2::scale_y_continuous(
        limits = y_limits,
        breaks = y_breaks
      )
  }
  
  return(gg_plot)
}